Repository gladguys/aluco, pull requests merged in 2019-11, with the labels that each got.

#75 Improve 58
  assets/images/alunos_chairs_sliver.jpeg
  assets/images/alunos_sliver.jpeg
  assets/images/turma_sliver.jpeg
  lib/screen/classes/class_home/class_students/class_students_screen.dart
  lib/screen/classes/list_classes/list_classes_screen.dart
  lib/screen/student/list_students_screen.dart
  lib/widget/al_scaffold_slivered.dart
Labels: enhancement

#94 Feature grade exam
  lib/model/exam_grade_dto.dart
  lib/model/grades_wrapper.dart
  lib/repository/api/API.dart
  lib/repository/api/class_repository.dart
  lib/repository/api/exam_repository.dart
  lib/repository/core/abstract_exam_repository.dart
  lib/screen/exam/components/details_exam.dart
  lib/screen/exam/components/exam_tile.dart
  lib/screen/exam/components/save_exam_button.dart
  lib/screen/exam/components/save_exam_form.dart
  lib/screen/exam/exam_bloc.dart
  lib/screen/exam/exam_detail_screen.dart
  lib/screen/exam/exams_screen.dart
  lib/theme/main_theme.dart
  lib/widget/al_scaffold.dart
  lib/widget/al_scaffold_slivered.dart
  lib/widget/delegate/student_search_delegate.dart
  lib/widget/empty_state/exam_empty_state.dart
  pubspec.lock
  pubspec.yaml
Labels: MOBILE

#105 Feature students grades
  lib/model/exam_grade_dto.dart
  lib/model/student_grades.dart
  lib/repository/api/class_repository.dart
  lib/repository/core/abstract_class_repository.dart
  lib/screen/classes/class_home/class_home_actions.dart
  lib/screen/classes/grade_board/components/student_grades_list.dart
  lib/screen/classes/grade_board/grade_board_bloc.dart
  lib/screen/classes/grade_board/grade_board_screen.dart
  lib/screen/exam/exam_bloc.dart
  lib/screen/exam/exam_detail_screen.dart
  lib/utils/al_number_format.dart
  pubspec.lock
  pubspec.yaml
Labels: MOBILE

#120 Loading
  lib/core/bloc/global_blocs.dart
  lib/core/bloc/linear_loading_bloc.dart
  lib/core/bloc/loading_bloc.dart
  lib/core/interceptor/loading_interceptor.dart
  lib/core/routing/al_router.dart
  lib/core/utils/form_utils.dart
  lib/core/utils/jwt_utils.dart
  lib/global_blocs.dart
  lib/main.dart
  lib/model/student.dart
  lib/repository/dio/dio_builder.dart
  lib/repository/dio/dio_config.dart
  lib/screen/classes/class_home/class_students/class_students_screen.dart
  lib/screen/classes/class_home/class_students/components/list_add_student_class.dart
  lib/screen/classes/list_classes/components/class_tile.dart
  lib/screen/classes/list_classes/components/save_class_button.dart
  lib/screen/classes/list_classes/components/save_class_form.dart
  lib/screen/classes/list_classes/save_class_screen.dart
  lib/screen/exam/components/exam_tile.dart
  lib/screen/exam/components/save_exam_button.dart
  lib/screen/exam/components/save_exam_form.dart
  lib/screen/exam/save_exam_screen.dart
  lib/screen/signin/components/create_account_button.dart
  lib/screen/signin/components/signin_form.dart
  lib/screen/signin/components/signin_form_button.dart
  lib/screen/signin/signin_bloc.dart
  lib/screen/signin/signin_screen.dart
  lib/screen/signup/components/have_account_button.dart
  lib/screen/signup/components/signup_form.dart
  lib/screen/signup/components/signup_form_button.dart
  lib/screen/signup/signup_screen.dart
  lib/screen/student/components/save_student_button.dart
  lib/screen/student/components/save_student_form.dart
  lib/screen/student/components/student_tile.dart
  lib/screen/student/save_student_screen.dart
  lib/widget/al_icon_text_vertical_button.dart
  lib/widget/al_scaffold.dart
  lib/widget/al_scaffold_slivered.dart
Labels: MOBILE

#129 Blocking when not on same day
  lib/screen/exam/components/details_exam.dart
  lib/screen/exam/exam_detail_screen.dart
Labels: MOBILE

#146 Issue 130
  lib/screen/exam/components/details_exam.dart
  lib/screen/exam/components/exam_tile.dart
  lib/screen/exam/exam_detail_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: MOBILE

#145 Adding empty screen for grade board
  lib/screen/classes/grade_board/grade_board_screen.dart
  lib/widget/empty_state/grade_board_empty_state.dart
Labels: MOBILE

#147 Issue 139
  lib/screen/classes/class_home/class_students/components/add_student_class_button.dart
  lib/screen/classes/class_home/class_students/components/list_add_student_class.dart
  lib/screen/exam/exam_detail_screen.dart
  lib/screen/home/home_screen.dart
  lib/utils/al_number_format.dart
  lib/widget/empty_state/exam_grade_student_empty_state.dart
  pubspec.lock
Labels: MOBILE, improvement

#148 Improve first login intro
  lib/core/utils/jwt_utils.dart
  lib/core/utils/pref_utils.dart
  lib/main.dart
  lib/screen/intro/into_screen.dart
  lib/screen/intro/intro_pages.dart
  lib/screen/intro/profile_image_picker.dart
  lib/screen/signin/components/signin_form_button.dart
  lib/screen/signin/signin_bloc.dart
  pubspec.lock
  pubspec.yaml
Labels: MOBILE, enhancement
